FROM python:3.12-slim

WORKDIR /mlflow

# instalăm mlflow O SINGURĂ DATĂ la build, nu la fiecare pornire
RUN pip install --no-cache-dir mlflow

# aici vor sta baza mlflow.db și artefactele
VOLUME /mlflow

EXPOSE 5000

CMD ["mlflow", "server","--host", "0.0.0.0","--port", "5000","--backend-store-uri", "sqlite:///mlflow.db","--default-artifact-root", "/mlflow/artifacts","--allowed-hosts", "mlflow:5000,localhost:*"]